name:                elfbot
version:             0.1.0.0
github:              "mstksg/elfbot"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2019"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mstksg/elfbot#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wredundant-constraints
- -Werror=incomplete-patterns

dependencies:
- base >= 4.7 && < 5
- conduit
- time
- text
- transformers
- megaparsec
- finite-typelits
- advent-of-code-api
- containers
- servant
- servant-client
- servant-client-core
- intervals

library:
  source-dirs: src

# executables:
#   elfbot-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - elfbot

# tests:
#   elfbot-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - elfbot
