name:                santabot
version:             0.1.0.0
github:              "mstksg/santabot"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2019"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mstksg/santabot#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wredundant-constraints
- -Werror=incomplete-patterns

dependencies:
- advent-of-code-api
- base >= 4.7 && < 5
- conduit
- containers
- finite-typelits
- intervals
- megaparsec
- servant
- servant-client
- servant-client-core
- simpleirc
- stm
- stm-chans
- stm-conduit
- text
- time
- transformers

library:
  source-dirs: src

executables:
  santabot:
    main:                santabot.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - santabot
    - yaml
    - aeson

# tests:
#   santabot-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - santabot
