name:                santabot
version:             0.1.0.0
github:              "mstksg/santabot"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2019"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Advent of Code utility IRC bot
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         "See me online at freenode ##advent-of-code!"

ghc-options:
- -Wall
- -Wcompat
- -Wredundant-constraints
- -Werror=incomplete-patterns

dependencies:
- base >= 4.7 && < 5
- advent-of-code-api >= 0.2.7

library:
  source-dirs: src
  dependencies:
  - bytestring
  - casing
  - conduino
  - conduit
  - containers
  - deepseq
  - dhall
  - directory
  - filepath
  - finite-typelits
  - free
  - html-entities
  - http-client
  - http-client-tls
  - http-conduit
  - human-readable-duration
  - intervals
  - linear
  - machines
  - megaparsec
  - modern-uri
  - mtl
  - nonempty-containers
  - parser-combinators
  - prettyprinter
  - profunctors
  - random
  - servant
  - servant-client-core
  - simpleirc
  - slack-api
  - stm
  - stm-chans
  - stm-conduit
  - tagsoup
  - text
  - th-printf
  - time
  - transformers
  - uri-bytestring
  - yaml

executables:
  santabot-irc:
    main:                santabot-irc.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - conduit
    - containers
    - http-client-tls
    - http-conduit
    - mtl
    - santabot
    - text
    - th-printf
    - time
    - yaml
  santabot-slack:
    main:                santabot-slack.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # dependencies:
    # - linklater
    # - warp
    # - aeson
    # - conduit
    # - containers
    # - http-client-tls
    # - http-conduit
    # - mtl
    # - santabot
    # - text
    # - th-printf
    # - time
    # - yaml


# tests:
#   santabot-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - santabot
